# built for Mid-360 DATASET (no other sensors). Testing the ROS2 FASTLIO -> bridge -> Wavemap pipeline
#  Can confirm it's working



map:
  general:
    world_frame: "camera_init" # map frame from FASTLIO2
    thresholding_period: { seconds: 2.0 }
    pruning_period: { seconds: 10.0 }
    publication_period: { seconds: 1.0 }
    logging_level: debug
    allow_reset_map_service: true
  data_structure:
    type: hashed_chunked_wavelet_octree
    min_cell_width: { meters: 0.01 }
    # tree_height: 9 #WHAT IS THIS FOR???

inputs:
######################### TESTING DEPTH_IMAGE INTEGRATOR TYPE #########################
# THIS ONE WORKS!!!!! FINE TUNE
  - type: depth_image
    general:
      topic_name: "/d435_front/d435_front/depth/image_rect_raw" # WORKS
      # topic_name: "/d435f_1/d435f_1/aligned_depth_to_color/image_raw" # DOES NOT WORK
      topic_queue_length: 30
      max_wait_for_pose: { seconds: 2.0 }
      time_offset: { seconds: -0.01} # Unsure of value for D435f, imu to cam is +0.013387
      depth_scale_factor: 0.001 # D435 depth scale is 1mm, don't change
      # reprojected_pointcloud_topic_name: "/wavemap/depth_cam_input"
    integrators:
      - integration_method:
          type: hashed_chunked_wavelet_integrator
          min_range: { meters: 0.2 }
          max_range: { meters: 1.0 }
          termination_update_error: 0.1
          # termination_height: 0
        projection_model:
          type: pinhole_camera_projector
          width: 848
          height: 480
          fx: 427.29736328125
          fy: 427.29736328125
          cx: 432.1024475097656
          cy: 236.54649353027344
        measurement_model:
          type: continuous_ray
          range_sigma: { meters: 0.005 }
          scaling_free: 0.4
          scaling_occupied: 0.8
  # # add anothter later
  # #     - integration_method:
  # #         type: hashed_chunked_wavelet_integrator
  # #         min_range: { meters: 1.0 }
  # #         max_range: { meters: 3.0 }
  # #         termination_update_error: 0.1
  # #         termination_height: 1
  # #       projection_model:
  # #         type: pinhole_camera_projector
  # #         width: 848
  # #         height: 480
  # #         fx: 427.29736328125
  # #         fy: 427.29736328125
  # #         cx: 432.1024475097656
  # #         cy: 236.54649353027344
  # #       measurement_model:
  # #         type: continuous_ray
  # #         range_sigma: { meters: 0.01 }
  # #         scaling_free: 0.4
  # #         scaling_occupied: 0.8
